deploy: search-app-tailwind Deploy
stage: deploy
only:
- main
script:
- apt-get update -qq && apt-get install -y -qq lftp
- lftp -c "set ftp:ssl-allow no; open -u search-app-tailwind-UI@mikeldicesteros.com,$painisapain ftp.cerra-wollstein.com; mirror -Rev dist/ ./public_html --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"